# -*- coding: utf-8 -*-
"""ConvIQ_DataScience.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8m5J2nm9AppMy-F0vqWOkXcg0wjYmQV

# ConvIQ — Inteligência Conversacional
## Data Science and Statistical Computing — **Sprint 3**
### Challenge FIAP × TOTVS 2026 — Engenharia de Software, 2º Ano

> **Entrega da Sprint 3:** classificação supervisionada de trechos de transcrição em categorias de
> negócio. As seções 01 a 06 constroem o pipeline de NLP (base herdada das sprints anteriores);
> as seções **07 a 12** cobrem os itens avaliados nesta sprint.

---

**Integrantes do grupo:**

| Nome | RM |
|------|----|
| Gustavo Estevam Cocchi | RM562472 |
| José Henrique Escobar Rizzo | RM564419 |
| Arthur Pastorello Dias Temistocle | RM562345 |
| Kazys Dzigan Tatarunas | RM564020 |
| Juan Pablo Molina Molina| RM564445 |


> Todas as bibliotecas usadas já vêm pré-instaladas no Colab.

---

## Setup — imports e download de recursos

Importamos as bibliotecas do pipeline de NLP e baixamos as *stopwords* em português do NLTK.
"""



import re
import unicodedata
from collections import Counter

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import nltk
from nltk.corpus import stopwords

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split, LeaveOneOut, cross_val_predict
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    confusion_matrix, ConfusionMatrixDisplay, classification_report,
    accuracy_score, precision_score, recall_score, f1_score
)

# Recursos do NLTK (rodar uma vez)
nltk.download('stopwords', quiet=True)

plt.rcParams['figure.figsize'] = (9, 4.5)
plt.rcParams['axes.grid'] = True
plt.rcParams['grid.alpha'] = 0.3
pd.set_option('display.max_colwidth', 60)

print('Ambiente pronto.')

"""## 01 — Entendimento do problema

### Contexto
A TOTVS realiza dezenas de reuniões de vendas e de *Customer Success* (CS) diariamente. Após
cada reunião, o vendedor registra notas no CRM — mas essas notas são **incompletas, subjetivas
e demoradas**, e grande parte do conhecimento real da conversa se perde. Sinais valiosos como a
intenção de troca por um concorrente, uma oportunidade de *upsell* ou a insatisfação do cliente
ficam soterrados no diálogo e nunca viram ação comercial.

### Objetivo do projeto
O **ConvIQ** é uma plataforma de Inteligência Conversacional que recebe a **transcrição em texto**
de uma reunião, processa o conteúdo com técnicas de NLP e extrai automaticamente sinais
estratégicos de negócio — transformando diálogos desestruturados em inteligência acionável.

### O que a IA identifica em cada transcrição
| Sinal | Descrição | Exemplo |
|-------|-----------|---------|
| Produto atual | Produto TOTVS que o cliente já usa | Protheus no backoffice |
| Oportunidade | Produto que o cliente pode comprar | Módulo RM para RH |
| Risco de churn | Menção a concorrente ou insatisfação | Viu demo da Senior |
| Budget | Valor financeiro mencionado | R$ 50.000 |
| Sentimento | Tom geral da conversa | Satisfeito / frustrado |
| Persona | Perfil do interlocutor | Gestor operacional / decisor técnico |

### Aplicações de negócio
- **Priorização da carteira:** identificar clientes em risco de *churn* antes da renovação.
- **Geração de pipeline:** detectar oportunidades de *upsell/cross-sell* automaticamente.
- **Coaching de vendas:** medir tom e equilíbrio da conversa entre vendedor e cliente.
- **Memória organizacional:** histórico estruturado e pesquisável de toda a carteira.

### Escopo deste notebook (disciplina Data Science)
Este notebook cobre o **núcleo técnico** do pipeline: ingestão e limpeza do texto, *feature
engineering* com TF-IDF, análise exploratória e geração de insights de negócio a partir das
transcrições. A persistência (Oracle) e a exibição (Java/DDD) são tratadas nas demais disciplinas.

### Dataset de trabalho — transcrições sintéticas

Como ainda não há transcrições reais disponíveis (risco mapeado na documentação do projeto),
criamos um **dataset sintético** de reuniões fictícias da TOTVS, baseado no exemplo do próprio
desafio. O dataset traz variedade proposital de produtos (Protheus, RM, Fluig, Datasul),
concorrentes (Senior, SAP, Oracle, Sankhya), sentimentos e personas — para exercitar todas as
etapas do pipeline.

> Este **mesmo dataset** alimenta as outras disciplinas (banco Oracle e testes do Java),
> garantindo coesão entre as entregas.
"""

# Dataset sintetico de reunioes TOTVS (vendas e Customer Success)
reunioes = [
    {"id_reuniao": 1, "data": "2026-05-04", "tipo": "Vendas", "cliente": "Industria Alfa",
     "participante": "Carlos Mendes", "cargo": "Gestor de Operacoes",
     "texto": "A gente usa o Protheus no backoffice ha tres anos e esta funcionando muito bem, "
              "o financeiro adora. O problema mesmo e o RH, ainda fazemos folha quase tudo no manual "
              "e na planilha. Seria otimo ter um modulo de RH integrado ao que ja temos. Gostei bastante "
              "da apresentacao, faz sentido para a gente avancar nisso."},

    {"id_reuniao": 2, "data": "2026-05-05", "tipo": "Vendas", "cliente": "Varejo Beta",
     "participante": "Fernanda Lima", "cargo": "Diretora Comercial",
     "texto": "Olha, vou ser sincera. A gente esta usando o Protheus mas andei vendo uma demo da Senior "
              "semana passada e fiquei interessada. O contrato de voces esta caro e o suporte demora. "
              "Temos um budget de uns 50.000 reais para resolver isso esse ano, mas preciso de motivos "
              "para continuar com a TOTVS."},

    {"id_reuniao": 3, "data": "2026-05-06", "tipo": "Customer Success", "cliente": "Logistica Gama",
     "participante": "Roberto Alves", "cargo": "Diretor de TI",
     "texto": "Estamos muito satisfeitos com o Datasul, virou a espinha dorsal da operacao. Agora queremos "
              "automatizar os processos de aprovacao que ainda sao no e-mail. Ouvi falar do Fluig, isso "
              "resolveria nosso fluxo de documentos? Se sim quero entender melhor, parece exatamente o que precisamos."},

    {"id_reuniao": 4, "data": "2026-05-07", "tipo": "Customer Success", "cliente": "Saude Delta",
     "participante": "Patricia Souza", "cargo": "Gerente Administrativa",
     "texto": "Para ser franca estou bem frustrada. Abrimos varios chamados e o suporte nao resolve. "
              "A diretoria ja esta pedindo para avaliar o SAP como alternativa. Se a situacao do suporte "
              "nao melhorar rapido vai ficar dificil justificar a renovacao do contrato."},

    {"id_reuniao": 5, "data": "2026-05-08", "tipo": "Vendas", "cliente": "Educacao Epsilon",
     "participante": "Joao Pereira", "cargo": "Coordenador Financeiro",
     "texto": "Somos uma instituicao de ensino e hoje nao temos um sistema de gestao integrado. "
              "Estou avaliando opcoes para financeiro e RH. Quanto custaria o pacote da TOTVS para uns "
              "duzentos funcionarios? Preciso levar uma proposta com valores para a mantenedora aprovar."},

    {"id_reuniao": 6, "data": "2026-05-11", "tipo": "Vendas", "cliente": "Agro Zeta",
     "participante": "Marina Castro", "cargo": "Diretora Financeira",
     "texto": "O Datasul nos atende muito bem no agronegocio. Estamos crescendo e abrindo duas filiais, "
              "entao queremos expandir os modulos. Tenho interesse em fiscal e tambem no modulo de RH. "
              "A experiencia tem sido excelente, confio na plataforma para escalar com a gente."},

    {"id_reuniao": 7, "data": "2026-05-12", "tipo": "Customer Success", "cliente": "Construtora Eta",
     "participante": "Eduardo Ramos", "cargo": "Gerente de Projetos",
     "texto": "A implantacao do Protheus atrasou demais e isso travou nosso cronograma. Estou insatisfeito "
              "com os prazos. O sistema em si e bom mas a entrega ficou muito aquem do prometido. Preciso "
              "que isso seja resolvido senao vamos reavaliar o investimento."},

    {"id_reuniao": 8, "data": "2026-05-13", "tipo": "Vendas", "cliente": "Servicos Theta",
     "participante": "Luiza Martins", "cargo": "Decisora Tecnica",
     "texto": "Somos prospect, ainda nao usamos nada de voces. Estou comparando o Protheus com o Sankhya. "
              "Tecnicamente preciso entender integracao via API e seguranca. O preco importa mas o que pesa "
              "mesmo na minha decisao e a robustez tecnica da solucao."},

    {"id_reuniao": 9, "data": "2026-05-14", "tipo": "Customer Success", "cliente": "Industria Iota",
     "participante": "Antonio Dias", "cargo": "Controller",
     "texto": "Usamos o Protheus ha mais de cinco anos sem grandes problemas, esta tudo estavel. "
              "Agora a diretoria quer dados melhores para decisao. Voces tem alguma solucao de analytics "
              "ou BI que conecte no Protheus? Adoraria ver dashboards dos nossos indicadores."},

    {"id_reuniao": 10, "data": "2026-05-15", "tipo": "Customer Success", "cliente": "Comercio Kappa",
     "participante": "Sandra Oliveira", "cargo": "Socia-Proprietaria",
     "texto": "O orcamento esta bem apertado esse ano. Estou pensando seriamente em nao renovar o contrato, "
              "que esta em torno de 30.000. Nao e que o sistema seja ruim, e questao de custo mesmo. "
              "Preciso enxergar valor claro para manter o investimento."},

    {"id_reuniao": 11, "data": "2026-05-18", "tipo": "Vendas", "cliente": "Tech Lambda",
     "participante": "Rafael Gomes", "cargo": "CIO",
     "texto": "Adoramos a plataforma. Ja usamos o RM para RH e queremos integrar com o Fluig para "
              "automatizar onboarding e aprovacoes. Temos budget aprovado de 120.000 para o projeto "
              "esse semestre. Estou muito otimista, quero fechar isso rapido."},

    {"id_reuniao": 12, "data": "2026-05-19", "tipo": "Customer Success", "cliente": "Distribuidora Mu",
     "participante": "Claudia Nunes", "cargo": "Gerente de RH",
     "texto": "No geral estamos contentes. O RM funciona bem para a folha, mas o modulo de ponto trava "
              "as vezes e isso irrita o time. Fora esse detalhe a experiencia e positiva. Queria so "
              "entender se tem atualizacao prevista para corrigir esse ponto."},

    {"id_reuniao": 13, "data": "2026-05-20", "tipo": "Vendas", "cliente": "Hospital Nu",
     "participante": "Bruno Teixeira", "cargo": "Diretor Administrativo",
     "texto": "Estamos em processo de escolha de ERP. A Oracle entrou na concorrencia com uma proposta "
              "agressiva. Gostei do Protheus na demo mas preciso comparar custo e suporte. A decisao final "
              "sai mes que vem, entao e agora que voces precisam mostrar diferencial."},

    {"id_reuniao": 14, "data": "2026-05-21", "tipo": "Customer Success", "cliente": "Cooperativa Xi",
     "participante": "Helena Barros", "cargo": "Diretora Executiva",
     "texto": "Experiencia excelente, ate indiquei a TOTVS para uma cooperativa parceira. Usamos o Protheus "
              "no fiscal e agora queremos o modulo tributario para dar conta da complexidade da reforma. "
              "Confiamos muito na plataforma, podem contar com a gente como referencia."},
]

df = pd.DataFrame(reunioes)
df["data"] = pd.to_datetime(df["data"])
print(f"Total de reunioes no dataset: {len(df)}")
print(f"Por tipo:\n{df['tipo'].value_counts().to_string()}")
df[["id_reuniao", "tipo", "cliente", "cargo"]].head()

"""## 02 — Ingestão e preparação do texto

Antes de extrair *features*, o texto precisa ser **normalizado**. Esta é a etapa de pré-processamento,
crítica em qualquer pipeline de NLP — texto sujo gera *features* ruins. Aplicamos, em ordem:

1. **Lowercase** — uniformiza maiúsculas/minúsculas (`Protheus` e `protheus` viram o mesmo token).
2. **Remoção de pontuação e números** — removemos símbolos que não carregam significado semântico.
3. **Remoção de acentos** — opcional, mas reduz a fragmentação do vocabulário em português.
4. **Remoção de stopwords** — palavras muito frequentes e pouco informativas (`de`, `a`, `que`...).
5. **Normalização de espaços** — colapsa múltiplos espaços em um só.

> Mantemos a coluna `texto` original e criamos uma nova coluna `texto_limpo`, para sempre podermos
> auditar a transformação.
"""

# Stopwords em portugues + termos genericos de conversa que nao agregam sinal
stop_pt = set(stopwords.words('portuguese'))
stop_extra = {"voces", "voce", "gente", "agora", "ainda", "muito", "bem", "ser",
              "ja", "so", "fica", "ficar", "vai", "ter", "tem", "preciso", "quero",
              "queremos", "estamos", "estou", "olha", "entao", "isso", "esse", "essa"}
stop_total = stop_pt | stop_extra

def remover_acentos(texto):
    nfkd = unicodedata.normalize('NFKD', texto)
    return ''.join(c for c in nfkd if not unicodedata.combining(c))

def limpar_texto(texto):
    texto = texto.lower()                              # 1. lowercase
    texto = remover_acentos(texto)                     # 3. remove acentos
    texto = re.sub(r'[^a-z\s]', ' ', texto)            # 2. remove pontuacao e numeros
    tokens = texto.split()
    tokens = [t for t in tokens if t not in stop_total and len(t) > 2]  # 4. stopwords + tokens curtos
    return ' '.join(tokens)                            # 5. normaliza espacos

df["texto_limpo"] = df["texto"].apply(limpar_texto)

# Comparacao antes / depois (primeira reuniao)
print("ANTES:\n", df.loc[0, "texto"][:200], "...\n")
print("DEPOIS:\n", df.loc[0, "texto_limpo"][:200], "...")

# Estatisticas da limpeza: quanto reduzimos o tamanho do texto
df["n_palavras_orig"] = df["texto"].str.split().apply(len)
df["n_palavras_limpo"] = df["texto_limpo"].str.split().apply(len)
df["reducao_%"] = (1 - df["n_palavras_limpo"] / df["n_palavras_orig"]) * 100

resumo = df[["cliente", "n_palavras_orig", "n_palavras_limpo", "reducao_%"]].round(1)
print(resumo.to_string(index=False))
print(f"\nReducao media de tokens apos limpeza: {df['reducao_%'].mean():.1f}%")

"""## 03 — Feature Engineering com TF-IDF

O **TF-IDF** (*Term Frequency – Inverse Document Frequency*) transforma cada transcrição em um vetor
numérico, onde cada dimensão é uma palavra do vocabulário. O peso de um termo cresce quanto mais ele
aparece **naquela** reunião (TF) e diminui quanto mais ele aparece em **todas** as reuniões (IDF).
O resultado: termos que distinguem uma reunião das demais recebem peso alto; termos genéricos, peso baixo.

### Justificativa dos parâmetros escolhidos
| Parâmetro | Valor | Por quê |
|-----------|-------|---------|
| `ngram_range` | `(1, 2)` | Captura unigramas e bigramas. `risco churn` ou `modulo rh` carregam mais sinal juntos do que separados. |
| `min_df` | `2` | Ignora termos que aparecem em só 1 reunião — provável ruído idiossincrático. |
| `max_df` | `0.85` | Descarta termos presentes em mais de 85% dos docs — quase stopwords no nosso domínio. |
| `sublinear_tf` | `True` | Usa `1 + log(tf)` em vez de `tf` puro, suavizando o efeito de repetições. |

Em um corpus pequeno como o nosso, esses limiares evitam que o vetorizador crie milhares de colunas
inúteis e concentra a matriz nos termos realmente discriminativos.
"""

vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.85,
    sublinear_tf=True
)

X = vectorizer.fit_transform(df["texto_limpo"])
vocab = vectorizer.get_feature_names_out()

print(f"Formato da matriz TF-IDF: {X.shape[0]} reunioes x {X.shape[1]} termos")
print(f"Densidade da matriz: {X.nnz / (X.shape[0] * X.shape[1]):.1%} (esparsa, como esperado)")
print(f"\nExemplos de termos do vocabulario:\n{list(vocab[:25])}")

# Termos com maior peso TF-IDF medio em todo o corpus (mais discriminativos no geral)
peso_medio = np.asarray(X.mean(axis=0)).ravel()
ranking = pd.DataFrame({"termo": vocab, "tfidf_medio": peso_medio})
ranking = ranking.sort_values("tfidf_medio", ascending=False).head(15)
print("Top 15 termos mais relevantes (TF-IDF medio):")
print(ranking.to_string(index=False))

# Para uma reuniao especifica, quais termos a definem?
def termos_da_reuniao(idx, top=8):
    linha = X[idx].toarray().ravel()
    top_idx = linha.argsort()[::-1][:top]
    return [(vocab[i], round(linha[i], 3)) for i in top_idx if linha[i] > 0]

for idx in [1, 3, 10]:  # Varejo Beta (churn), Logistica Gama (upsell), Comercio Kappa (budget)
    print(f"Reuniao #{df.loc[idx, 'id_reuniao']} - {df.loc[idx, 'cliente']}:")
    print("  ", termos_da_reuniao(idx), "\n")

"""## 04 — Análise exploratória (EDA)

Agora exploramos padrões de linguagem no corpus: termos mais frequentes, distribuição por tipo de
reunião e o comprimento dos diálogos. O objetivo é entender o vocabulário do domínio comercial da
TOTVS antes de extrair os sinais de negócio.
"""

# Frequencia absoluta de termos (CountVectorizer para contagem bruta)
counter = CountVectorizer(ngram_range=(1, 1), min_df=1)
C = counter.fit_transform(df["texto_limpo"])
freq = np.asarray(C.sum(axis=0)).ravel()
termos_freq = pd.Series(freq, index=counter.get_feature_names_out()).sort_values(ascending=False)

top15 = termos_freq.head(15)
ax = top15[::-1].plot(kind="barh", color="#1D9E75")
ax.set_title("Top 15 termos mais frequentes no corpus")
ax.set_xlabel("Frequencia absoluta")
plt.tight_layout()
plt.show()

print("Tabela de frequencias (top 15):")
print(top15.to_frame("frequencia").to_string())

# Distribuicao do tamanho das transcricoes por tipo de reuniao
fig, axes = plt.subplots(1, 2, figsize=(11, 4))

df.boxplot(column="n_palavras_orig", by="tipo", ax=axes[0])
axes[0].set_title("Tamanho da transcricao por tipo")
axes[0].set_ylabel("Numero de palavras")
axes[0].set_xlabel("")

df["tipo"].value_counts().plot(kind="bar", ax=axes[1], color=["#534AB7", "#D85A30"])
axes[1].set_title("Quantidade de reunioes por tipo")
axes[1].set_ylabel("Reunioes")
axes[1].tick_params(axis="x", rotation=0)

plt.suptitle("")
plt.tight_layout()
plt.show()

# Padroes de linguagem: ocorrencia de termos-chave do dominio por reuniao
dominio = ["protheus", "datasul", "fluig", "concorrente", "suporte", "budget", "modulo"]
# observacao: alguns termos foram normalizados; checamos presenca no texto limpo
mapa = {
    "protheus": "protheus", "datasul": "datasul", "fluig": "fluig",
    "rh": "rh", "suporte": "suporte", "modulo": "modulo", "renovacao": "renov"
}
presenca = pd.DataFrame({
    rotulo: df["texto_limpo"].str.contains(chave).astype(int)
    for rotulo, chave in mapa.items()
}, index=df["cliente"])

plt.figure(figsize=(9, 5))
plt.imshow(presenca.values, aspect="auto", cmap="Greens")
plt.xticks(range(len(presenca.columns)), presenca.columns, rotation=45, ha="right")
plt.yticks(range(len(presenca.index)), presenca.index, fontsize=8)
plt.title("Mapa de calor: presenca de termos-chave por reuniao")
plt.colorbar(label="presente (1) / ausente (0)")
plt.tight_layout()
plt.show()

"""## 05 — Introdução a Embeddings

### TF-IDF vs. Embeddings

| Aspecto | TF-IDF | Embeddings (Word2Vec, BERT, OpenAI...) |
|---------|--------|----------------------------------------|
| Representação | Vetor **esparso** do tamanho do vocabulário | Vetor **denso** de dimensão fixa (ex.: 300, 768, 1536) |
| Significado | Conta ocorrência de palavras | Captura **significado e contexto** semântico |
| Sinônimos | `caro` e `custoso` são dimensões diferentes | Ficam **próximos** no espaço vetorial |
| Contexto | Ignora ordem e contexto | `banco` (assento) ≠ `banco` (financeiro) com modelos contextuais |
| Custo | Leve, rápido, interpretável | Pesado, exige modelo pré-treinado |
| Dados | Funciona bem com pouco texto | Brilha com volume e nuance |

### Por que começamos com TF-IDF no ConvIQ?
Para um corpus pequeno e um MVP, o TF-IDF é **transparente, rápido e interpretável** — conseguimos
explicar exatamente por que um termo pesou. É a base sobre a qual treinamos os classificadores das
seções 09 e 10.

### Quando migrar para embeddings?
Quando o ConvIQ escalar para milhares de reuniões e precisar entender que *"achei caro"*,
*"tá salgado"* e *"fora do orçamento"* significam a **mesma** insatisfação de preço — algo que o
TF-IDF, baseado em correspondência exata de palavras, não captura. Embeddings também habilitam busca
semântica ("encontre reuniões parecidas com esta") e classificação mais robusta de sentimento.

### Demonstração: similaridade entre reuniões com TF-IDF
Como ponte conceitual, calculamos a **similaridade do cosseno** entre os vetores TF-IDF. É exatamente
a mesma operação que se faria com embeddings — só muda a qualidade da representação por baixo.
"""

# Similaridade do cosseno entre todas as reunioes (matriz NxN)
sim = cosine_similarity(X)
sim_df = pd.DataFrame(sim, index=df["cliente"], columns=df["cliente"])

# Para a reuniao da Varejo Beta (churn), quais reunioes sao mais parecidas?
alvo = "Varejo Beta"
parecidas = sim_df[alvo].sort_values(ascending=False)[1:4]
print(f"Reunioes mais semelhantes a '{alvo}':")
print(parecidas.to_string())

plt.figure(figsize=(8, 6.5))
plt.imshow(sim, cmap="Purples")
plt.xticks(range(len(df)), df["cliente"], rotation=90, fontsize=7)
plt.yticks(range(len(df)), df["cliente"], fontsize=7)
plt.title("Similaridade do cosseno entre reunioes (base TF-IDF)")
plt.colorbar(label="similaridade")
plt.tight_layout()
plt.show()

"""## 06 — Insights de negócio

Aqui o pipeline entrega valor. Combinamos o TF-IDF com **listas de palavras-chave por categoria**
(estratégia de mitigação prevista na documentação: complementar o modelo estatístico com regras de
domínio) para extrair, de cada reunião, os sinais de negócio do ConvIQ:

- **Sentimento** da conversa (positivo / neutro / negativo)
- **Risco de churn** (menção a concorrente ou insatisfação)
- **Oportunidade de upsell** (interesse em novos módulos)
- **Budget** mencionado
- **Produtos TOTVS** citados

Ao final, geramos um **card de inteligência** por reunião e um **painel agregado** da carteira —
prévia do dashboard que vira diferencial do projeto.
"""

# ---- Dicionarios de dominio (regras de negocio) ----
LEX_NEGATIVO = ["frustrad", "insatisfeit", "atras", "trav", "demora", "caro", "apertad",
                "problema", "irrita", "reavaliar", "nao renovar", "nao resolve", "dificil"]
LEX_POSITIVO = ["satisfeit", "adora", "excelente", "otimo", "gostei", "confio", "confia",
                "contente", "otimista", "muito bem", "indiquei", "referencia", "positiv"]
CONCORRENTES = ["senior", "sap", "oracle", "sankhya"]
SINAIS_UPSELL = ["modulo", "integrar", "expandir", "analytics", "tributario", "fluig",
                 "automatizar", "novos", "interesse"]
PRODUTOS_TOTVS = ["protheus", "datasul", "fluig", "rm", "analytics"]

def contar(texto, termos):
    return sum(texto.count(t) for t in termos)

def extrair_budget(texto_original):
    # procura padroes como "50.000", "30000", "120.000"
    achados = re.findall(r'(\d{1,3}(?:\.\d{3})+|\d{4,6})', texto_original.replace(" mil", "000"))
    valores = [int(a.replace(".", "")) for a in achados]
    valores = [v for v in valores if v >= 1000]
    return max(valores) if valores else None

def classificar_sentimento(pos, neg):
    if neg > pos and neg > 0:
        return "Negativo"
    if pos > neg and pos > 0:
        return "Positivo"
    return "Neutro"

def analisar_reuniao(row):
    t = row["texto"].lower()
    t = remover_acentos(t)
    pos = contar(t, LEX_POSITIVO)
    neg = contar(t, LEX_NEGATIVO)
    concorrente = [c for c in CONCORRENTES if c in t]
    # churn: mencao a concorrente, OU insatisfacao clara (mais negativo que positivo)
    churn = bool(concorrente) or (neg >= 2 and neg > pos)
    # upsell: interesse em novos modulos, desde que nao seja um caso de churn
    upsell = (not churn) and contar(t, SINAIS_UPSELL) >= 1
    produtos = [p.upper() if p in ("rm",) else p.capitalize()
                for p in PRODUTOS_TOTVS if re.search(rf'\b{p}\b', t)]
    return pd.Series({
        "sentimento": classificar_sentimento(pos, neg),
        "risco_churn": "ALTO" if churn else "Baixo",
        "concorrente": ", ".join(concorrente) if concorrente else "-",
        "oportunidade_upsell": "Sim" if upsell else "Nao",
        "budget_rs": extrair_budget(row["texto"]),
        "produtos": ", ".join(produtos) if produtos else "-",
    })

sinais = df.join(df.apply(analisar_reuniao, axis=1))
colunas_card = ["cliente", "tipo", "sentimento", "risco_churn", "concorrente",
                "oportunidade_upsell", "budget_rs", "produtos"]
print("=== Sinais extraidos de cada reuniao ===\n")
print(sinais[colunas_card].to_string(index=False))

# ---- Card de inteligencia individual (saida que iria para o gestor) ----
def card_inteligencia(idx):
    r = sinais.loc[idx]
    budget = f"R$ {int(r['budget_rs']):,}".replace(",", ".") if pd.notna(r["budget_rs"]) else "nao mencionado"
    print("+" + "-" * 54 + "+")
    print(f"| CARD CONVIQ  -  {r['cliente']:<37}|")
    print("+" + "-" * 54 + "+")
    print(f"| Tipo de reuniao : {r['tipo']:<35}|")
    print(f"| Interlocutor    : {r['participante']} ({r['cargo']})".ljust(55) + "|")
    print(f"| Sentimento      : {r['sentimento']:<35}|")
    print(f"| Risco de churn  : {r['risco_churn']:<35}|")
    print(f"| Concorrente     : {r['concorrente']:<35}|")
    print(f"| Upsell          : {r['oportunidade_upsell']:<35}|")
    print(f"| Budget          : {budget:<35}|")
    print(f"| Produtos TOTVS  : {r['produtos']:<35}|")
    print("+" + "-" * 54 + "+")

# Exemplos: um churn, um upsell, um neutro
for idx in [1, 10, 5]:
    card_inteligencia(idx)
    print()

# ---- Painel agregado da carteira (previa do dashboard / diferencial) ----
fig, axes = plt.subplots(1, 3, figsize=(13, 4))

# 1. Distribuicao de sentimento
sinais["sentimento"].value_counts().reindex(["Positivo", "Neutro", "Negativo"]).plot(
    kind="bar", ax=axes[0], color=["#1D9E75", "#888780", "#D85A30"])
axes[0].set_title("Sentimento da carteira")
axes[0].set_ylabel("Reunioes")
axes[0].tick_params(axis="x", rotation=0)

# 2. Clientes em risco de churn
risco = sinais["risco_churn"].value_counts()
axes[1].pie(risco, labels=risco.index, autopct="%1.0f%%",
            colors=["#888780", "#E24B4A"], startangle=90)
axes[1].set_title("Risco de churn na carteira")

# 3. Oportunidades de upsell
sinais["oportunidade_upsell"].value_counts().plot(
    kind="bar", ax=axes[2], color=["#534AB7", "#B4B2A9"])
axes[2].set_title("Oportunidades de upsell")
axes[2].set_ylabel("Reunioes")
axes[2].tick_params(axis="x", rotation=0)

plt.tight_layout()
plt.show()

# ---- Acoes recomendadas: priorizacao automatica da carteira ----
print("CLIENTES EM RISCO DE CHURN (acao imediata do time de CS):")
risco = sinais[sinais["risco_churn"] == "ALTO"][["cliente", "concorrente", "sentimento", "budget_rs"]]
print(risco.to_string(index=False))

print("\nTOP OPORTUNIDADES DE UPSELL (acao do time de vendas):")
opp = sinais[sinais["oportunidade_upsell"] == "Sim"][["cliente", "produtos", "budget_rs"]]
opp = opp.sort_values("budget_rs", ascending=False, na_position="last")
print(opp.to_string(index=False))

budget_total = sinais["budget_rs"].sum()
print(f"\nBudget total identificado na carteira: R$ {int(budget_total):,}".replace(",", "."))

"""## 07 — Preparação da variável-alvo e definição do problema  *(10 pts)*

### O problema de classificação
Até aqui, os sinais de negócio foram extraídos por **regras** (dicionários de palavras-chave). Regras
são transparentes, mas não generalizam: só reconhecem exatamente as palavras que escrevemos na lista.
A partir desta seção passamos para **aprendizado supervisionado** — o modelo aprende, a partir dos
exemplos, quais combinações de termos indicam risco, inclusive combinações que não anteciparíamos.

**Problema escolhido:** classificar cada reunião em **risco de churn — ALTO ou Baixo**.

Por que este e não os outros sinais:
- É **binário**, o que dá estimativas mais estáveis num corpus pequeno (14 reuniões) do que as 3
  classes de sentimento, que deixariam poucos exemplos por classe.
- É o sinal de **maior impacto financeiro**: perder um cliente custa muito mais caro que perder uma
  oportunidade de upsell.
- Conecta diretamente com a priorização de carteira, que é a aplicação de negócio principal do ConvIQ.

### De onde vem o rótulo (variável-alvo `y`)
Não temos um histórico real de clientes que cancelaram contrato. Usamos então como rótulo a saída do
motor de regras da seção 06 — técnica conhecida como ***weak labeling*** (rotulagem fraca): uma
heurística confiável o suficiente para iniciar o treino, até existirem rótulos reais.

> **Limitação metodológica — importante.** Como o rótulo vem da regra, as métricas medem quanto o
> modelo consegue **aprender e generalizar o comportamento da regra**, não quanto ele acerta a
> realidade do cliente. É o passo correto com os dados disponíveis, mas a validação definitiva exige
> que o time de CS confirme os casos reais. Retomamos isso na seção 12.

Convenção: `1 = ALTO` (classe positiva, o que queremos detectar) e `0 = Baixo`.
"""

y = (sinais["risco_churn"] == "ALTO").astype(int)
target_names = ["Baixo", "ALTO"]

print("Variavel-alvo (y) definida a partir do motor de regras da secao 06:\n")
print(pd.DataFrame({
    "cliente": sinais["cliente"],
    "risco_churn": sinais["risco_churn"],
    "y": y.values,
}).to_string(index=False))

"""## 08 — Análise das classes e eventual balanceamento  *(15 pts)*

Antes de treinar, precisamos saber se as classes estão equilibradas. Um conjunto muito desbalanceado
faz o modelo "chutar" sempre a classe majoritária e ainda assim exibir uma acurácia alta — o chamado
*paradoxo da acurácia*.
"""

contagem = y.value_counts().sort_index()
contagem.index = target_names
proporcao = (contagem / contagem.sum() * 100).round(1)

dist = pd.DataFrame({"reunioes": contagem, "%": proporcao})
print("Distribuicao das classes:")
print(dist.to_string())

baseline = contagem.max() / contagem.sum()
print(f"\nBaseline (classificador que sempre chuta a classe majoritaria): {baseline:.1%} de acuracia.")
print("Qualquer modelo precisa superar esse valor para ter alguma utilidade real.")

ax = dist["reunioes"].plot(kind="bar", color=["#888780", "#E24B4A"])
ax.set_title("Distribuicao das classes — risco de churn")
ax.set_ylabel("Numero de reunioes")
ax.tick_params(axis="x", rotation=0)
plt.tight_layout()
plt.show()

"""### Decisão sobre balanceamento

A distribuição ficou em **8 Baixo (57,1%) × 6 ALTO (42,9%)** — um desbalanceamento leve, longe de
cenários críticos (que costumam ser 90/10 ou piores).

**Decisão: não aplicar oversampling sintético (SMOTE).** Justificativa:

1. O desbalanceamento é pequeno; o ganho seria marginal.
2. SMOTE interpola vizinhos para criar amostras artificiais. Num espaço **TF-IDF esparso** com apenas
   14 documentos, esses pontos interpolados não correspondem a nenhum texto real e tenderiam a
   introduzir ruído em vez de sinal.
3. Existe alternativa melhor e sem dados sintéticos: **`class_weight="balanced"`**, que faz o próprio
   algoritmo penalizar mais os erros na classe minoritária durante o treino. É o que usamos na
   Logistic Regression.

> O Multinomial Naive Bayes não possui o parâmetro `class_weight` — ele lida com o desbalanceamento
> pelas probabilidades *a priori* de cada classe, estimadas diretamente dos dados.

### Verificando a decisão na prática

A justificativa acima não deve ficar no plano da opinião. Medimos o efeito real do balanceamento,
treinando a mesma Logistic Regression com e sem `class_weight`, sob a mesma validação (LOOCV):
"""

comparacao_balanceamento = []
for rotulo, peso in [("sem balanceamento (padrao)", None),
                     ("class_weight='balanced'", "balanced")]:
    modelo_bal = LogisticRegression(class_weight=peso, max_iter=1000, random_state=42)
    pred_bal = cross_val_predict(modelo_bal, X, y, cv=LeaveOneOut())
    tn, fp, fn, tp = confusion_matrix(y, pred_bal).ravel()
    comparacao_balanceamento.append({
        "configuracao": rotulo,
        "accuracy": accuracy_score(y, pred_bal),
        "precision": precision_score(y, pred_bal, zero_division=0),
        "recall": recall_score(y, pred_bal, zero_division=0),
        "f1": f1_score(y, pred_bal, zero_division=0),
        "clientes_em_risco_perdidos": fn,
    })

print("Efeito do balanceamento (Logistic Regression, LOOCV):")
print(pd.DataFrame(comparacao_balanceamento).round(3).to_string(index=False))

"""### O que a medição mostra

O efeito é muito maior do que o desbalanceamento "leve" sugeriria:

- **Sem balanceamento**, o modelo encontra apenas **1 dos 6** clientes em risco (recall 0.167) e deixa
  passar **5 falsos negativos** — o erro mais caro do nosso problema.
- Sua acurácia cai para **0.500**, ou seja, **abaixo do baseline de 57,1%** calculado acima. Um modelo
  que erra mais do que chutar sempre "Baixo" não tem utilidade alguma.
- É o **paradoxo da acurácia** em ação: sem penalizar erros na classe minoritária, o algoritmo aprende
  que o caminho mais fácil para reduzir o erro médio é quase nunca prever ALTO.

Com `class_weight="balanced"`, o recall salta para **0.833** e os falsos negativos caem de 5 para 1,
mantendo o mesmo número de falsos positivos (2). Ou seja: o ganho não veio de simplesmente "alertar
mais", e sim de **alertar melhor**.

> Conclusão: mesmo com desbalanceamento moderado, o tratamento era necessário — e o ajuste de pesos
> resolveu sem precisar inventar amostras sintéticas.

## 09 — Construção dos modelos de classificação  *(25 pts)*

Treinamos **dois algoritmos** sobre a mesma matriz TF-IDF construída na seção 03, para que a comparação
avalie os algoritmos — e não diferenças de pré-processamento.

| Modelo | Tipo | Por que entra na comparação |
|--------|------|------------------------------|
| **Multinomial Naive Bayes** | Generativo, probabilístico | Referência clássica para classificação de texto; assume independência entre termos, é rápido e funciona bem com poucos dados |
| **Logistic Regression** | Discriminativo, linear | Aprende um peso por termo, é interpretável (dá para ver quais palavras puxam para ALTO) e aceita `class_weight` para tratar desbalanceamento |

### Estratégia de validação
Com 14 amostras, um `train_test_split` isolado é **frágil**: o conjunto de teste fica com 4-5 reuniões,
e trocar uma única amostra muda drasticamente as métricas. Por isso usamos **duas estratégias
complementares**:

1. **Holdout estratificado (70/30)** — o split tradicional, mantendo a proporção das classes.
2. **Leave-One-Out Cross-Validation (LOOCV)** — treina 14 vezes, cada vez deixando **uma** reunião de
   fora para teste. Toda reunião é testada exatamente uma vez, e o modelo sempre treina com o máximo de
   dados disponível. É o padrão recomendado para datasets muito pequenos.

A comparação entre as duas estratégias é, por si só, um resultado relevante — mostramos isso na seção 10.
"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, stratify=y, random_state=42
)

print(f"Conjunto de treino: {X_train.shape[0]} reunioes")
print(f"Conjunto de teste : {X_test.shape[0]} reunioes")
print(f"Classes no teste  : {dict(zip(*np.unique(y_test, return_counts=True)))} (0=Baixo, 1=ALTO)")

modelos = {
    "Naive Bayes": MultinomialNB(),
    "Logistic Regression": LogisticRegression(
        class_weight="balanced", max_iter=1000, random_state=42
    ),
}

for nome, modelo in modelos.items():
    modelo.fit(X_train, y_train)
    print(f"{nome}: treinado.")

# Termos que mais empurram a previsao para ALTO (interpretabilidade da Logistic Regression)
coeficientes = modelos["Logistic Regression"].coef_.ravel()
top_alto = np.argsort(coeficientes)[::-1][:10]
print("\nTermos que mais indicam risco ALTO (pesos da Logistic Regression):")
print(pd.DataFrame({
    "termo": vocab[top_alto],
    "peso": coeficientes[top_alto].round(3),
}).to_string(index=False))

"""## 10 — Avaliação e comparação dos modelos  *(25 pts)*

### As métricas, traduzidas para o problema

Considerando `ALTO` (cliente em risco) como classe positiva:

| Métrica | Fórmula | O que significa aqui |
|---------|---------|----------------------|
| **Accuracy** | acertos / total | Proporção geral de acertos. Enganosa quando há desbalanceamento |
| **Precision** | VP / (VP + FP) | Dos clientes que o modelo alertou como em risco, quantos realmente estavam |
| **Recall** | VP / (VP + FN) | Dos clientes realmente em risco, quantos o modelo conseguiu encontrar |
| **F1-score** | média harmônica | Equilíbrio entre precision e recall |

### Qual métrica priorizar — e por quê

**Recall da classe ALTO.** A justificativa é o custo assimétrico dos dois tipos de erro:

- **Falso negativo** (modelo diz "Baixo", cliente estava em risco): o cliente cancela o contrato sem
  que ninguém tenha sido avisado. Custo = perda de receita recorrente + custo de reaquisição, que no
  mercado B2B costuma ser várias vezes maior que o de retenção.
- **Falso positivo** (modelo diz "ALTO", cliente estava bem): o time de CS faz um contato
  desnecessário. Custo = algumas horas de trabalho — e o contato proativo raramente prejudica a
  relação.

Como o falso negativo é ordens de grandeza mais caro, **preferimos um modelo que erre para o lado de
alertar demais**. Na prática, isso significa aceitar alguns alarmes falsos a mais em troca de deixar
passar menos clientes em risco — critério que aplicamos na comparação a seguir.
"""

def avaliar(y_true, y_pred, nome):
    return {
        "modelo": nome,
        "accuracy": accuracy_score(y_true, y_pred),
        "precision": precision_score(y_true, y_pred, zero_division=0),
        "recall": recall_score(y_true, y_pred, zero_division=0),
        "f1": f1_score(y_true, y_pred, zero_division=0),
    }

# ---- Estrategia 1: holdout 70/30 ----
resultados_holdout = [avaliar(y_test, m.predict(X_test), nome) for nome, m in modelos.items()]
print("=== Holdout estratificado (5 reunioes de teste) ===")
print(pd.DataFrame(resultados_holdout).round(3).to_string(index=False))

# ---- Estrategia 2: LOOCV sobre as 14 reunioes ----
predicoes_loocv = {
    nome: cross_val_predict(modelo, X, y, cv=LeaveOneOut())
    for nome, modelo in modelos.items()
}
resultados_loocv = [avaliar(y, pred, nome) for nome, pred in predicoes_loocv.items()]
print("\n=== Leave-One-Out Cross-Validation (todas as 14 reunioes) ===")
print(pd.DataFrame(resultados_loocv).round(3).to_string(index=False))

"""### Por que as duas estratégias discordam — e em qual confiar

No **holdout**, o Naive Bayes atinge 100% em todas as métricas. Esse número **não deve ser
comemorado**: o conjunto de teste tem apenas 5 reuniões, e acertar 5 de 5 é perfeitamente possível por
sorte no sorteio do split. Uma acurácia de 100% num teste desse tamanho é sinal de **amostra pequena
demais**, não de modelo perfeito.

O **LOOCV** avalia as 14 reuniões e mostra o quadro real: o Naive Bayes cai para recall 0.667, enquanto
a Logistic Regression alcança **recall 0.833**. Como o LOOCV usa toda a base e não depende de um
sorteio específico, **é nele que baseamos a decisão**.

Essa divergência é, em si, um resultado da análise: ela evidencia por que validar modelo em dataset
pequeno com um único split é arriscado.
"""

# Matrizes de confusao (LOOCV) lado a lado
fig, axes = plt.subplots(1, 2, figsize=(11, 4.5))
for ax, (nome, pred) in zip(axes, predicoes_loocv.items()):
    cm = confusion_matrix(y, pred)
    ConfusionMatrixDisplay(cm, display_labels=target_names).plot(
        ax=ax, cmap="Blues", colorbar=False
    )
    ax.set_title(f"{nome} (LOOCV)")
    ax.grid(False)
plt.tight_layout()
plt.show()

for nome, pred in predicoes_loocv.items():
    tn, fp, fn, tp = confusion_matrix(y, pred).ravel()
    print(f"--- {nome} (LOOCV) ---")
    print(f"  Verdadeiros ALTO detectados (VP): {tp}  |  Clientes em risco perdidos (FN): {fn}")
    print(f"  Alarmes falsos (FP)             : {fp}  |  Baixo risco confirmados (VN)   : {tn}")
    print(classification_report(y, pred, target_names=target_names, zero_division=0))

"""## 11 — Análise dos erros  *(15 pts)*

Métricas agregadas dizem *quanto* o modelo erra; a análise de erros diz *onde* e *por quê* — que é o
que permite melhorar o pipeline.
"""

for nome, pred in predicoes_loocv.items():
    erros = pred != y.values
    print(f"=== Erros do {nome} (LOOCV): {erros.sum()} de {len(y)} ===")
    if erros.any():
        detalhe = sinais.loc[erros, ["cliente", "risco_churn", "concorrente", "sentimento"]].copy()
        detalhe["previsto"] = [target_names[p] for p in pred[erros]]
        detalhe["tipo_erro"] = np.where(
            y.values[erros] == 1, "Falso Negativo (grave)", "Falso Positivo (tolerável)"
        )
        print(detalhe.to_string(index=False))
    print()

print("Texto das reunioes classificadas incorretamente pelo modelo escolhido:\n")
erros_lr = predicoes_loocv["Logistic Regression"] != y.values
for idx in df.index[erros_lr]:
    print(f"[{sinais.loc[idx, 'cliente']}] rotulo={sinais.loc[idx, 'risco_churn']}")
    print(f"  {df.loc[idx, 'texto'][:180]}...\n")

"""### O que os erros revelam

O modelo escolhido erra 3 das 14 reuniões, e os erros **não são aleatórios** — cada um expõe uma
limitação diferente do pipeline:

**1. Vocabulário comercial ambíguo — os dois falsos positivos.**
*Educação Epsilon* e *Indústria Iota* são conversas saudáveis (um prospect pedindo proposta e um
cliente satisfeito querendo analytics), mas foram sinalizadas como risco. Olhando os pesos da seção 09,
a causa fica clara: termos como `decisao`, `custo`, `contrato` e `investimento` estão entre os de maior
peso para ALTO — e aparecem com naturalidade tanto numa ameaça de cancelamento quanto numa negociação
comercial perfeitamente sadia. **O TF-IDF registra a presença da palavra, não a intenção por trás dela.**

**2. Rótulo questionável herdado da regra — o falso negativo.**
*Serviços Theta* é o caso mais interessante. A regra da seção 06 marcou ALTO porque o texto cita um
concorrente (Sankhya), mas a reunião é de um **prospect** — "ainda não usamos nada de vocês" — fazendo
comparação técnica. Uma empresa que ainda não é cliente **não tem contrato para cancelar**. O modelo
previu Baixo e foi penalizado nas métricas, mas discordar do rótulo foi provavelmente a resposta
**mais correta**. Este erro não é do modelo: é da heurística que gerou o rótulo — exatamente o risco
do *weak labeling* antecipado na seção 07.

**3. Negação tratada como token isolado.**
O termo `nao` aparece entre os de maior peso para ALTO, mas é profundamente ambíguo: em "não renovar o
contrato" indica risco real, enquanto em "não temos um sistema" ou "sem grandes problemas" é neutro ou
até positivo. Bag-of-words avalia o token sozinho, sem o que vem depois dele.

**Ações concretas derivadas desta análise:**
- **Corrigir a regra de rotulagem** para excluir prospects do risco de churn e separar "menção a
  concorrente" de "intenção declarada de troca" — isso melhora o rótulo antes de melhorar o modelo.
- Adicionar *features* que capturem **negação e intensidade** (ex.: bigramas de negação), hoje perdidas.
- Migrar para **embeddings** quando o corpus crescer, para capturar intenção e contexto (seção 05).

> Observação metodológica: a Logistic Regression corrigiu um dos falsos negativos do Naive Bayes
> (*Construtora Eta*, insatisfação sem menção a concorrente) — é justamente o tipo de caso que motivou
> a escolha do recall como métrica prioritária.

### Testando a hipótese: e se o rótulo for corrigido?

A análise acima não é só descritiva — ela produz uma **hipótese testável**: *se os prospects estão
poluindo o rótulo, tratá-los corretamente deve melhorar o desempenho*.

Vamos verificar. Primeiro identificamos os prospects pelo próprio texto, depois comparamos três
cenários de rotulagem sob a mesma validação (LOOCV):

| Cenário | Tratamento dos prospects |
|---------|--------------------------|
| **A** | Rótulo original (prospect marcado como ALTO por citar concorrente) |
| **B** | Prospect forçado para `Baixo` — permanece na base, mas sem risco de churn |
| **C** | Prospect **removido da população** — churn não é definido para quem não é cliente |
"""

# Deteccao de prospect: empresas que declaram nao ser clientes ainda
MARCAS_PROSPECT = ["somos prospect", "ainda nao usamos", "nao usamos nada",
                   "nao temos um sistema", "hoje nao temos"]

def eh_prospect(texto):
    t = remover_acentos(texto.lower())
    return any(marca in t for marca in MARCAS_PROSPECT)

df["is_prospect"] = df["texto"].apply(eh_prospect)
print("Reunioes identificadas como prospect (cliente sem contrato vigente):")
print(df.loc[df["is_prospect"], ["cliente", "tipo"]].to_string(index=False))

def avaliar_cenario(textos, alvo, nome_cenario):
    """Revetoriza e roda LOOCV nos dois modelos para um cenario de rotulagem."""
    vec = TfidfVectorizer(ngram_range=(1, 2), min_df=2, max_df=0.85, sublinear_tf=True)
    X_cen = vec.fit_transform(textos)
    linhas = []
    candidatos = {
        "Naive Bayes": MultinomialNB(),
        "Logistic Regression": LogisticRegression(
            class_weight="balanced", max_iter=1000, random_state=42),
    }
    for nome, modelo in candidatos.items():
        pred = cross_val_predict(modelo, X_cen, alvo, cv=LeaveOneOut())
        linha = avaliar(alvo, pred, nome)
        linha["cenario"] = nome_cenario
        linha["n"] = len(alvo)
        linhas.append(linha)
    return linhas

# Cenario A - rotulo original
comparativo = avaliar_cenario(df["texto_limpo"], y, "A. Rotulo original")

# Cenario B - prospect forcado para Baixo
y_b = y.copy()
y_b[df["is_prospect"].values] = 0
comparativo += avaliar_cenario(df["texto_limpo"], y_b, "B. Prospect = Baixo")

# Cenario C - prospect removido da populacao
mantem = ~df["is_prospect"].values
comparativo += avaliar_cenario(
    df.loc[mantem, "texto_limpo"],
    y[mantem].reset_index(drop=True),
    "C. Prospect excluido",
)

tabela_cenarios = pd.DataFrame(comparativo)[
    ["cenario", "modelo", "n", "accuracy", "precision", "recall", "f1"]
]
print("\nComparacao dos cenarios de rotulagem (LOOCV):")
print(tabela_cenarios.round(3).to_string(index=False))

"""### Leitura dos resultados — com o mesmo ceticismo da seção 10

**A hipótese se confirma: os prospects estavam mesmo poluindo o rótulo.** Para a Logistic Regression,
corrigi-los melhora accuracy (0.786 → 0.857), precision (0.714 → 0.800) e F1 (0.769 → 0.800) no
cenário B, com uma queda pequena de recall (0.833 → 0.800) — troca aceitável, já que o falso negativo
eliminado era justamente o rótulo incorreto.

**Mas atenção ao cenário C.** Removendo os prospects, *ambos* os modelos atingem 1.000 em todas as
métricas. Seria fácil declarar vitória — e seria **o mesmo erro que criticamos na seção 10**, quando o
Naive Bayes marcou 100% no holdout. A leitura correta é:

- O resultado **não** significa que o modelo é perfeito. Significa que, removidas as 2 conversas
  ambíguas, as 12 restantes ficam **linearmente separáveis** neste vocabulário minúsculo.
- Com 12 amostras, "acertar todas" é um feito modesto: basta que nenhum par de reuniões de classes
  opostas compartilhe vocabulário decisivo.
- A explicação mecânica também é clara: as reuniões de prospect eram as que injetavam o vocabulário
  comercial neutro (`custo`, `decisao`, `proposta`) que confundia o modelo sobre os clientes ativos.
  Retiradas elas, o termo ambíguo perde peso — e o falso positivo da *Indústria Iota* desaparece.

**Nota sobre o Naive Bayes:** no cenário B ele *piora* (recall 0.667 → 0.400). A correção não beneficia
os dois algoritmos igualmente — mais um argumento a favor da Logistic Regression, que se mostrou mais
robusta a mudanças na definição do rótulo.

### Conclusão do experimento

A decisão metodologicamente correta é o **cenário C**: risco de churn só é definido para quem tem
contrato, então prospects não pertencem a esta população. Não adotamos esse recorte como resultado
principal desta sprint por uma razão de honestidade — ele reduz a base para 12 amostras e produz
métricas perfeitas que **não sobreviveriam a dados reais**. Os números reportados nas seções 10 e 12
seguem sendo os do cenário A, mais conservadores.

O que este experimento entrega é mais valioso que um número melhor: **a confirmação de que o gargalo do
ConvIQ hoje é a qualidade do rótulo, não a escolha do algoritmo.** Trocar Naive Bayes por Logistic
Regression mudou o F1 em 0.10; corrigir a definição do alvo mudou em 0.23 no mesmo cenário. É onde o
próximo esforço deve ir.

## 12 — Conclusões e implicações para o negócio  *(10 pts)*

### Modelo selecionado: Logistic Regression

| Critério | Naive Bayes | Logistic Regression |
|----------|-------------|---------------------|
| Recall (ALTO) — métrica prioritária | 0.667 | **0.833** |
| F1-score | 0.667 | **0.769** |
| Accuracy | 0.714 | **0.786** |
| Clientes em risco não detectados (FN) | 2 | **1** |
| Interpretabilidade | Baixa | **Alta** (peso por termo) |

A Logistic Regression vence no critério que definimos como prioritário: **detecta 5 dos 6 clientes em
risco, contra 4 do Naive Bayes**. Na prática, isso é um cliente a mais que a operação de CS consegue
abordar antes da renovação. Ela ainda oferece os pesos por termo, o que permite explicar ao vendedor
*por que* uma reunião foi sinalizada — requisito para que a recomendação seja adotada.

### Implicações para o negócio
- **Priorização da carteira:** o modelo transforma leitura manual de transcrições numa fila ordenada
  por risco, permitindo que o CS atue antes da renovação, e não depois do pedido de cancelamento.
- **Custo do erro é assimétrico e o modelo respeita isso:** ele foi calibrado para alertar demais em
  vez de deixar passar — a postura correta quando o falso negativo significa perder um contrato.
- **Decisão explicável:** os pesos por termo mostram quais trechos motivaram o alerta, o que sustenta
  a confiança do time comercial na ferramenta.

### Limitações (honestas) e próximos passos
1. **Dataset sintético e pequeno.** 14 reuniões fictícias. As métricas indicam viabilidade do
   pipeline, não desempenho esperado em produção.
2. **Rótulo por regra (*weak label*).** Como discutido na seção 07, o modelo aprendeu a reproduzir a
   heurística. A validação real exige que o CS confirme quais clientes de fato cancelaram — é a peça
   que fecha o ciclo e depende das disciplinas de Database Design (tabela de feedback) e Java/DDD
   (endpoint de correção).
3. **TF-IDF não captura tom nem negação.** Origem direta dos falsos negativos da seção 11; resolvido
   com embeddings quando houver volume.
4. **Falta a etapa de voz → texto.** O pipeline hoje parte de texto pronto; reuniões reais são áudio,
   e a integração com Whisper é pré-requisito para uso real.

### Onde investir o próximo esforço

O experimento da seção 11 respondeu isso com número, e não com intuição. Comparando o tamanho dos dois
efeitos sobre o F1:

| Mudança | Ganho de F1 |
|---------|-------------|
| Trocar o algoritmo (Naive Bayes → Logistic Regression) | +0.10 |
| Corrigir a definição do alvo (excluir prospects) | **+0.23** |

**Melhorar o rótulo valeu mais que o dobro de melhorar o algoritmo.** A implicação prática é direta:
não faz sentido investir em modelos mais sofisticados — XGBoost, embeddings, redes neurais — enquanto a
variável-alvo vier de uma heurística que confunde prospect com cliente. O retorno está em definir bem o
problema e coletar rótulo humano, não em trocar de estimador.

> **Ponte para a Sprint 4:** o modelo selecionado aqui vira o núcleo do fluxo
> `Transcrição → Processamento → Modelo → Indicadores → Recomendação`, empacotado num protótipo
> funcional que recebe uma transcrição nova e devolve o card de inteligência completo. A prioridade
> técnica, conforme a tabela acima, é adotar o recorte de população validado na seção 11 e começar a
> coletar confirmações do time de CS.

## Conclusão geral

Este notebook evoluiu o ConvIQ de um extrator baseado em regras para um pipeline com **aprendizado
supervisionado de fato**: definimos a variável-alvo, analisamos o balanceamento das classes, treinamos
e comparamos dois algoritmos com validação adequada ao tamanho da base, investigamos os erros e
traduzimos o resultado em implicações de negócio.

**Integração com as demais disciplinas:**
- **Database Design:** persistir transcrições, sinais e o feedback do CS no Oracle.
- **Java/DDD:** expor os cards via API Restful, incluindo o endpoint de correção do risco.
- **AR/VR:** apresentar o card de inteligência na experiência do usuário final.
"""